### ISSUE TITLE
婦女保障名額

### ISSUE THREAD

**Issue by clkao** [g0v/partyvote2016#10]

**Comment by yurenju** [comment]
轉貼自 FB

別忘記選罷法有不分區名額婦女不得低於二分之一的規定，然後各黨的名單不知道在亂提什麼，於是你們的工作更複雜了：

(1)民進黨
15席：順位16林靜儀當選，而非順位15鍾孔炤
17席：順位19周春米當選，而非順位17徐國勇
18席：順位20李麗芬當選，而非順位18施義芳
21→23 / 22→24 / 25→26 / 27→28 / 29→30 / 31→32 / 33→34

(2)親民黨
5席：順位6何偉真當選 而非 順位5楊紫宗
11→12

(4)和平鴿聯盟黨
只有一位女性所以第三席不可能拿到

(6)民國黨 (前三順位都男性是來亂的嗎= = )
2席：順位4蔡慧玲當選，而非順位2林錫維
3席：順位6何宇玲當選，而非順位3陳奕樵
5→7 / 7→9

(7)信心希望聯盟
5→6

(8)中華統一促進黨
3→4 / 5→6 / 7→8 / 9→10

(9)國民黨
3→4 / 5→7 / 7→9 / 9→10 / 11→12 / 13→14

(10)臺聯
3→4 / 5→6 / 7→8 / 9→10 / 11→12 / 13→14

(12)大愛憲改聯盟
2→3 / 3→4 / 5→6

(13)綠黨社會民主黨聯盟
3→4 / 5→6

(14)臺灣獨立黨
只提一位男性.........

(15)無盟
只有三位女性所以第七席不可能拿到

(17)健保免費連線
只有一位女性所以第三席不可能拿到
