### ISSUE TITLE
不好意思請忽略這個 issue.... (要怎麼刪除呀？@@)

### ISSUE THREAD

**Issue by repertoire1202** [g0v/partyvote2016#13]
![image](https://cloud.githubusercontent.com/assets/16625994/12217515/ff69b140-b73d-11e5-924b-dff0df5bc469.png)

民進黨 44.00%；國民黨 30.00%；時代力量  12.00%；親民黨 7.00%；綠黨社會民主黨聯盟 7.00% 的時候，綠黨應該要有 3 席，因為增額錄取為 35 席，原因在於席次基數小數點排名相同只能都各給一席了。

**Comment by MrOrz** [comment]
@yurenju please close this issue

**Comment by MrOrz** [comment]
@repertoire1202 請點下面的 close issue 按鈕唷。目前只有 @yurenju 與開啟 issue 的你可以 close issue。

參考圖：http://i.stack.imgur.com/vRuSR.png
