### ISSUE TITLE
民進黨 40.00%；國民黨 30.00%；時代力量	10.00%；親民黨 10.00%；綠黨社會民主黨聯盟 10.00% 的時候，時代力量應該要有 4 席才對，因為增額錄取成 35 席，原因在於席次基數小數點排名相同，且時代力量柯劭臻是女的。(圖好像貼錯了不好意思，綠黨聯盟詹順貴是男的可惜，不然也要多一席，整個不分區立委變成 36 席)

### ISSUE THREAD

**Issue by repertoire1202** [g0v/partyvote2016#14]
![image](https://cloud.githubusercontent.com/assets/16625994/12217579/c56c11d4-b73f-11e5-9d1e-f0da46246197.png)

**Comment by yurenju** [comment]
@repertoire1202 請問一下這個規則要在哪裡找到啊？我現在是套用這個規則 http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=D0020010&FLNO=67

**Comment by MrOrz** [comment]
@repertoire1202 
嗯我也沒看到「增額錄取」的規定耶，目前算法是按照 http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=D0020010&FLNO=67 的這個規定：

「依前款規定分配當選名額後，如有剩餘名額，應按各政黨分配當選名額後之剩餘數大小，依序分配剩餘名額。剩餘數相同時，以抽籤決定之。」

也就是說，(ㄅ黨 40%, ㄆ黨 30%, ㄇ黨 10%, ㄈ黨 10%, ㄉ黨 10%) 的狀況底下，我們是這樣算的：

```
ㄅ黨：
34 * 40% = 13.6 ⋯⋯ 分配得 13 席，剩餘數 0.6

ㄆ黨：
34 * 30% = 10.2 ⋯⋯ 分配得 10 席，剩餘數 0.2

ㄇ、ㄈ、ㄉ黨：
34 * 10% = 3.4 ⋯⋯ 分配得 3 席，剩餘數 0.4

13+10+3+3+3 = 32，離 34 席總數，還缺 2 席。
其中 1 席給剩餘數最大的ㄅ黨，ㄅ黨最後得 14 席；
最後 1 席，由於ㄇ、ㄈ、ㄉ黨剩餘數相同，實際上是要抽籤，但程式是隨便給其中一個黨（例如說ㄇ黨），然後那個黨就會多一席。
```

然後就會得到你附圖那樣的結果。

**Comment by repertoire1202** [comment]
謝謝！我搞錯了！長知識！！
