### ISSUE TITLE
第一階段未超過5%也會算入不分區分配名單

### ISSUE THREAD

**Issue by aldrinni** [g0v/partyvote2016#15]
民44% 親5.5% 國32.1% 時10.6% 綠社4.6%  當check 無效票的時候會發生
綠社會有兩席 : ) 與現行制度不符

**Comment by aldrinni** [comment]
自問自答  Somehow 現在改好了  剛剛不知道為什麼會有這個問題..

**Comment by clkao** [comment]
其實這是正確的，因為無效票不計入第一階段的計算，所以實際的綠社得票率是 `4.6% / (1-44%-5.5%-32.1%-10.6%) =~ 5.8%`，但是應該要在介面上顯示正確的第一階段得票率（也是在 input box 後面？）

**Comment by clkao** [comment]
也可以考慮再加一個 slider 是全部未滿 5% 的政黨得票總和

**Comment by aldrinni** [comment]
<5% 在第一階段應該就算是無效票, 好像規定是這樣的. 我google也是這樣

**Comment by clkao** [comment]
是這樣沒錯，但是那個 <5% 是已經去掉「無效票」的了，所以被剔除的應該是稱為第二階段的無效票，跟亂蓋或空白那種無效票是不同的意義。

可以參考 2012 選舉的得票：
- [選舉概況](http://db.cec.gov.tw/histQuery.jsp?voteCode=20120101T4A2&qryType=prof) - 有效票 13162072 無效票 283619
- [第一階段](http://db.cec.gov.tw/histFile?voteCode=20120101T1A2&resourceCode=C2) - 總計政黨得票為上述有效票
- [第二階段](http://db.cec.gov.tw/histFile?voteCode=20120101T1A2&resourceCode=C3)

這邊勾選的效果是將剩下未分配的視為那 283619 票，所以原本「佔總票數的百分比」變成「佔有效票的百分比」可能會變成超過 5%

**Comment by aldrinni** [comment]
這樣說好了
改成民30 親30 國15 時10  綠社4.6 
不Check無效票的話  席次不對
Check 無效票  綠社會有席次  
如果可以考慮選擇的時候也會把小於5% 不論check不check 自動在第二階段變成0  會比較方便比較

**Comment by clkao** [comment]
先加上「尚未完成分配」的訊息好了，因為沒分完（還沒操作完成）、當作無效票、當作未達門檻的總票數 其實是三個不同的意義，現在只有同一個介面想要表達其中兩種。

先放在這邊：https://g0v.github.io/partyvote2016/

**Comment by aldrinni** [comment]
可以再做個建議嗎? 省略Check box  
1. 未分配比例 <15% , 不分區才開始算席次
2. 低於<5%, 不計入第二階段
這樣可能更user-friendly
