### ISSUE TITLE
應該考慮政黨所提的席次

### ISSUE THREAD

**Issue by yurenju** [g0v/partyvote2016#3]
比如說時代力量只有提名六席，那他拿到的席次不應該超過 6

**Comment by Conjuror** [comment]
可以順便把其它黨放上來嗎？

**Comment by yurenju** [comment]
@Conjuror 全上了！

**Comment by clkao** [comment]
依[選罷法§67 IV](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=D0020010&FLNO=67)，超出的名額會從缺，也可以表示出來。

**Comment by yurenju** [comment]
喔喔好，如果是從缺的話還蠻好算的
