### ISSUE TITLE
讀取民調數值

### ISSUE THREAD

**Issue by lanfon72** [g0v/partyvote2016#9]
1. [Wikipedia](http://www.wikiwand.com/zh-tw/2016%E5%B9%B4%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B%E7%AB%8B%E6%B3%95%E5%A7%94%E5%93%A1%E9%81%B8%E8%88%89#/.E5.8D.80.E5.9F.9F.E6.9A.A8.E5.8E.9F.E4.BD.8F.E6.B0.91.E9.81.B8.E8.88.89_2) 有提供各時間點的民調數值。(但一月初各家的封關民調會較準確)
2. 讀取多家民調依累進加權取平均值。(以各民調的樣本數做為分母)

在 2. 的情況下 **理想上** 應該會比較接近最後結果(不包含未表態)....

**Comment by yurenju** [comment]
@lanfon72 民調可能不能放，選舉前十天引用民調會有觸法的可能

**Comment by lanfon72** [comment]
忘了這件事...........
那應該可以提供個位置載入外部資源做為 `參考` (?
